<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>divDefaultModalContainer</name>
   <tag></tag>
   <elementGuidId>7c63b1f7-3657-40cb-af9e-98ae7c29420a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]//div[@class=&quot;modal-container&quot;][count(. | //div[@ref_element = 'Object Repository/vuejs/modal/iframeResult']) = count(//div[@ref_element = 'Object Repository/vuejs/modal/iframeResult'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]//div[@class=&quot;modal-container&quot;]</value>
   </webElementProperties>
</WebElementEntity>
