<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframeResult</name>
   <tag></tag>
   <elementGuidId>a6243969-ad4c-4978-ae8e-8d02c15956f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[contains(@src, '//fiddle.jshell.net/yyx990803/mwLbw11k/show/light/') and @ref_element = 'Object Repository/vuejs/modal/iframeExamples']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//fiddle.jshell.net/yyx990803/mwLbw11k/show/light/</value>
   </webElementProperties>
</WebElementEntity>
